### ISSUE TITLE
Provided Docker Compose.YML error and fix

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [theupdateframework/notary#1535]
Hello `notary`, 

* the `docker-compose.yml` file at root of repo has one error, for `notary` version `f255ae779066dc28ae4aee196061e58bb38a2b49` (commit hash)
* the problem is that the mysql db is unreachable because the port mapping configuration is missing

* Here below Iadded port mapping to `3306` : 

```Yaml
version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    networks:
      - mdb
      - sig
    ports:
      - "8080"
      - "4443:4443"
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-server -config=fixtures/server-config.json"
    depends_on:
      - mysql
      - signer
  signer:
    build:
      context: .
      dockerfile: signer.Dockerfile
    networks:
      mdb:
      sig:
        aliases:
          - notarysigner
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-signer -config=fixtures/signer-config.json"
    depends_on:
      - mysql
  mysql:
    networks:
      - mdb
    volumes:
      - ./notarysql/mysql-initdb.d:/docker-entrypoint-initdb.d
      - notary_data:/var/lib/mysql
    image: mariadb:10.4
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    command: mysqld --innodb_file_per_table
    ports:
      - 3306:3306
    expose:
      - 3306
volumes:
  notary_data:
    external: false
networks:
  mdb:
    external: false
  sig:
    external: false
```
